/*
 * THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 * This file was generated by the dom/make_names.pl script.
 *
 * Copyright (C) 2005, 2006, 2007, 2008, 2009 Apple Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "config.h"
#include "V8SVGElementWrapperFactory.h"

#if ENABLE(SVG)

#include "V8SVGAElement.h"
#include "V8SVGAltGlyphElement.h"
#include "V8SVGAnimateElement.h"
#include "V8SVGAnimateColorElement.h"
#include "V8SVGAnimateTransformElement.h"
#include "V8SVGCircleElement.h"
#include "V8SVGClipPathElement.h"
#include "V8SVGCursorElement.h"
#include "V8SVGDefsElement.h"
#include "V8SVGDescElement.h"
#include "V8SVGEllipseElement.h"
#include "V8SVGFEBlendElement.h"
#include "V8SVGFEColorMatrixElement.h"
#include "V8SVGFEComponentTransferElement.h"
#include "V8SVGFECompositeElement.h"
#include "V8SVGFEConvolveMatrixElement.h"
#include "V8SVGFEDiffuseLightingElement.h"
#include "V8SVGFEDisplacementMapElement.h"
#include "V8SVGFEDistantLightElement.h"
#include "V8SVGFEFloodElement.h"
#include "V8SVGFEFuncAElement.h"
#include "V8SVGFEFuncBElement.h"
#include "V8SVGFEFuncGElement.h"
#include "V8SVGFEFuncRElement.h"
#include "V8SVGFEGaussianBlurElement.h"
#include "V8SVGFEImageElement.h"
#include "V8SVGFEMergeElement.h"
#include "V8SVGFEMergeNodeElement.h"
#include "V8SVGFEMorphologyElement.h"
#include "V8SVGFEOffsetElement.h"
#include "V8SVGFEPointLightElement.h"
#include "V8SVGFESpecularLightingElement.h"
#include "V8SVGFESpotLightElement.h"
#include "V8SVGFETileElement.h"
#include "V8SVGFETurbulenceElement.h"
#include "V8SVGFilterElement.h"
#include "V8SVGFontElement.h"
#include "V8SVGFontFaceElement.h"
#include "V8SVGFontFaceFormatElement.h"
#include "V8SVGFontFaceNameElement.h"
#include "V8SVGFontFaceSrcElement.h"
#include "V8SVGFontFaceUriElement.h"
#include "V8SVGForeignObjectElement.h"
#include "V8SVGGElement.h"
#include "V8SVGGlyphElement.h"
#include "V8SVGImageElement.h"
#include "V8SVGLineElement.h"
#include "V8SVGLinearGradientElement.h"
#include "V8SVGMarkerElement.h"
#include "V8SVGMaskElement.h"
#include "V8SVGMetadataElement.h"
#include "V8SVGMissingGlyphElement.h"
#include "V8SVGPathElement.h"
#include "V8SVGPatternElement.h"
#include "V8SVGPolygonElement.h"
#include "V8SVGPolylineElement.h"
#include "V8SVGRadialGradientElement.h"
#include "V8SVGRectElement.h"
#include "V8SVGScriptElement.h"
#include "V8SVGSetElement.h"
#include "V8SVGStopElement.h"
#include "V8SVGStyleElement.h"
#include "V8SVGSVGElement.h"
#include "V8SVGSwitchElement.h"
#include "V8SVGSymbolElement.h"
#include "V8SVGTextElement.h"
#include "V8SVGTextPathElement.h"
#include "V8SVGTitleElement.h"
#include "V8SVGTRefElement.h"
#include "V8SVGTSpanElement.h"
#include "V8SVGUseElement.h"
#include "V8SVGViewElement.h"
#include "V8SVGVKernElement.h"

#include "SVGNames.h"

#include "SVGAElement.h"
#include "SVGAltGlyphElement.h"
#include "SVGAnimateElement.h"
#include "SVGAnimateColorElement.h"
#include "SVGAnimateMotionElement.h"
#include "SVGAnimateTransformElement.h"
#include "SVGCircleElement.h"
#include "SVGClipPathElement.h"
#include "SVGCursorElement.h"
#include "SVGDefsElement.h"
#include "SVGDescElement.h"
#include "SVGEllipseElement.h"
#include "SVGFEBlendElement.h"
#include "SVGFEColorMatrixElement.h"
#include "SVGFEComponentTransferElement.h"
#include "SVGFECompositeElement.h"
#include "SVGFEConvolveMatrixElement.h"
#include "SVGFEDiffuseLightingElement.h"
#include "SVGFEDisplacementMapElement.h"
#include "SVGFEDistantLightElement.h"
#include "SVGFEFloodElement.h"
#include "SVGFEFuncAElement.h"
#include "SVGFEFuncBElement.h"
#include "SVGFEFuncGElement.h"
#include "SVGFEFuncRElement.h"
#include "SVGFEGaussianBlurElement.h"
#include "SVGFEImageElement.h"
#include "SVGFEMergeElement.h"
#include "SVGFEMergeNodeElement.h"
#include "SVGFEMorphologyElement.h"
#include "SVGFEOffsetElement.h"
#include "SVGFEPointLightElement.h"
#include "SVGFESpecularLightingElement.h"
#include "SVGFESpotLightElement.h"
#include "SVGFETileElement.h"
#include "SVGFETurbulenceElement.h"
#include "SVGFilterElement.h"
#include "SVGFontElement.h"
#include "SVGFontFaceElement.h"
#include "SVGFontFaceFormatElement.h"
#include "SVGFontFaceNameElement.h"
#include "SVGFontFaceSrcElement.h"
#include "SVGFontFaceUriElement.h"
#include "SVGForeignObjectElement.h"
#include "SVGGElement.h"
#include "SVGGlyphElement.h"
#include "SVGHKernElement.h"
#include "SVGImageElement.h"
#include "SVGLineElement.h"
#include "SVGLinearGradientElement.h"
#include "SVGMarkerElement.h"
#include "SVGMaskElement.h"
#include "SVGMetadataElement.h"
#include "SVGMissingGlyphElement.h"
#include "SVGMPathElement.h"
#include "SVGPathElement.h"
#include "SVGPatternElement.h"
#include "SVGPolygonElement.h"
#include "SVGPolylineElement.h"
#include "SVGRadialGradientElement.h"
#include "SVGRectElement.h"
#include "SVGScriptElement.h"
#include "SVGSetElement.h"
#include "SVGStopElement.h"
#include "SVGStyleElement.h"
#include "SVGSVGElement.h"
#include "SVGSwitchElement.h"
#include "SVGSymbolElement.h"
#include "SVGTextElement.h"
#include "SVGTextPathElement.h"
#include "SVGTitleElement.h"
#include "SVGTRefElement.h"
#include "SVGTSpanElement.h"
#include "SVGUseElement.h"
#include "SVGViewElement.h"
#include "SVGVKernElement.h"
#include <wtf/StdLibExtras.h>

#if ENABLE(VIDEO)
#include "Document.h"
#include "Settings.h"
#endif

#include "V8SVGElement.h"
        
#include <v8.h>

namespace WebCore {

using namespace SVGNames;

typedef v8::Handle<v8::Value> (*CreateSVGElementWrapperFunction)(SVGElement*);

static v8::Handle<v8::Value> createSVGAElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGAElement*>(element));
}


static v8::Handle<v8::Value> createSVGAltGlyphElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGAltGlyphElement*>(element));
}


static v8::Handle<v8::Value> createSVGAnimateElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGAnimateElement*>(element));
}


static v8::Handle<v8::Value> createSVGAnimateColorElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGAnimateColorElement*>(element));
}


static v8::Handle<v8::Value> createSVGAnimateTransformElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGAnimateTransformElement*>(element));
}


static v8::Handle<v8::Value> createSVGCircleElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGCircleElement*>(element));
}


static v8::Handle<v8::Value> createSVGClipPathElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGClipPathElement*>(element));
}


static v8::Handle<v8::Value> createSVGCursorElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGCursorElement*>(element));
}


static v8::Handle<v8::Value> createSVGDefsElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGDefsElement*>(element));
}


static v8::Handle<v8::Value> createSVGDescElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGDescElement*>(element));
}


static v8::Handle<v8::Value> createSVGEllipseElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGEllipseElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEBlendElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEBlendElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEColorMatrixElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEColorMatrixElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEComponentTransferElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEComponentTransferElement*>(element));
}


static v8::Handle<v8::Value> createSVGFECompositeElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFECompositeElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEConvolveMatrixElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEConvolveMatrixElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEDiffuseLightingElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEDiffuseLightingElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEDisplacementMapElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEDisplacementMapElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEDistantLightElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEDistantLightElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEFloodElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEFloodElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEFuncAElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEFuncAElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEFuncBElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEFuncBElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEFuncGElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEFuncGElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEFuncRElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEFuncRElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEGaussianBlurElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEGaussianBlurElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEImageElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEImageElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEMergeElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEMergeElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEMergeNodeElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEMergeNodeElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEMorphologyElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEMorphologyElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEOffsetElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEOffsetElement*>(element));
}


static v8::Handle<v8::Value> createSVGFEPointLightElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFEPointLightElement*>(element));
}


static v8::Handle<v8::Value> createSVGFESpecularLightingElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFESpecularLightingElement*>(element));
}


static v8::Handle<v8::Value> createSVGFESpotLightElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFESpotLightElement*>(element));
}


static v8::Handle<v8::Value> createSVGFETileElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFETileElement*>(element));
}


static v8::Handle<v8::Value> createSVGFETurbulenceElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFETurbulenceElement*>(element));
}


static v8::Handle<v8::Value> createSVGFilterElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFilterElement*>(element));
}


static v8::Handle<v8::Value> createSVGFontElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFontElement*>(element));
}


static v8::Handle<v8::Value> createSVGFontFaceElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFontFaceElement*>(element));
}


static v8::Handle<v8::Value> createSVGFontFaceFormatElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFontFaceFormatElement*>(element));
}


static v8::Handle<v8::Value> createSVGFontFaceNameElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFontFaceNameElement*>(element));
}


static v8::Handle<v8::Value> createSVGFontFaceSrcElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFontFaceSrcElement*>(element));
}


static v8::Handle<v8::Value> createSVGFontFaceUriElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGFontFaceUriElement*>(element));
}


static v8::Handle<v8::Value> createSVGForeignObjectElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGForeignObjectElement*>(element));
}


static v8::Handle<v8::Value> createSVGGElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGGElement*>(element));
}


static v8::Handle<v8::Value> createSVGGlyphElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGGlyphElement*>(element));
}


static v8::Handle<v8::Value> createSVGImageElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGImageElement*>(element));
}


static v8::Handle<v8::Value> createSVGLineElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGLineElement*>(element));
}


static v8::Handle<v8::Value> createSVGLinearGradientElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGLinearGradientElement*>(element));
}


static v8::Handle<v8::Value> createSVGMarkerElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGMarkerElement*>(element));
}


static v8::Handle<v8::Value> createSVGMaskElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGMaskElement*>(element));
}


static v8::Handle<v8::Value> createSVGMetadataElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGMetadataElement*>(element));
}


static v8::Handle<v8::Value> createSVGMissingGlyphElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGMissingGlyphElement*>(element));
}


static v8::Handle<v8::Value> createSVGPathElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGPathElement*>(element));
}


static v8::Handle<v8::Value> createSVGPatternElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGPatternElement*>(element));
}


static v8::Handle<v8::Value> createSVGPolygonElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGPolygonElement*>(element));
}


static v8::Handle<v8::Value> createSVGPolylineElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGPolylineElement*>(element));
}


static v8::Handle<v8::Value> createSVGRadialGradientElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGRadialGradientElement*>(element));
}


static v8::Handle<v8::Value> createSVGRectElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGRectElement*>(element));
}


static v8::Handle<v8::Value> createSVGScriptElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGScriptElement*>(element));
}


static v8::Handle<v8::Value> createSVGSetElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGSetElement*>(element));
}


static v8::Handle<v8::Value> createSVGStopElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGStopElement*>(element));
}


static v8::Handle<v8::Value> createSVGStyleElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGStyleElement*>(element));
}


static v8::Handle<v8::Value> createSVGSVGElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGSVGElement*>(element));
}


static v8::Handle<v8::Value> createSVGSwitchElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGSwitchElement*>(element));
}


static v8::Handle<v8::Value> createSVGSymbolElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGSymbolElement*>(element));
}


static v8::Handle<v8::Value> createSVGTextElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGTextElement*>(element));
}


static v8::Handle<v8::Value> createSVGTextPathElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGTextPathElement*>(element));
}


static v8::Handle<v8::Value> createSVGTitleElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGTitleElement*>(element));
}


static v8::Handle<v8::Value> createSVGTRefElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGTRefElement*>(element));
}


static v8::Handle<v8::Value> createSVGTSpanElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGTSpanElement*>(element));
}


static v8::Handle<v8::Value> createSVGUseElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGUseElement*>(element));
}


static v8::Handle<v8::Value> createSVGViewElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGViewElement*>(element));
}


static v8::Handle<v8::Value> createSVGVKernElementWrapper(SVGElement* element)
{
    return toV8(static_cast<SVGVKernElement*>(element));
}


v8::Handle<v8::Value> createV8SVGWrapper(SVGElement* element, bool forceNewObject)
{
    typedef HashMap<WTF::AtomicStringImpl*, CreateSVGElementWrapperFunction> FunctionMap;
    DEFINE_STATIC_LOCAL(FunctionMap, map, ());
    if (map.isEmpty()) {
       map.set(aTag.localName().impl(), createSVGAElementWrapper);
       map.set(altGlyphTag.localName().impl(), createSVGAltGlyphElementWrapper);
       map.set(animateTag.localName().impl(), createSVGAnimateElementWrapper);
       map.set(animateColorTag.localName().impl(), createSVGAnimateColorElementWrapper);
       map.set(animateTransformTag.localName().impl(), createSVGAnimateTransformElementWrapper);
       map.set(circleTag.localName().impl(), createSVGCircleElementWrapper);
       map.set(clipPathTag.localName().impl(), createSVGClipPathElementWrapper);
       map.set(cursorTag.localName().impl(), createSVGCursorElementWrapper);
       map.set(defsTag.localName().impl(), createSVGDefsElementWrapper);
       map.set(descTag.localName().impl(), createSVGDescElementWrapper);
       map.set(ellipseTag.localName().impl(), createSVGEllipseElementWrapper);
       map.set(feBlendTag.localName().impl(), createSVGFEBlendElementWrapper);
       map.set(feColorMatrixTag.localName().impl(), createSVGFEColorMatrixElementWrapper);
       map.set(feComponentTransferTag.localName().impl(), createSVGFEComponentTransferElementWrapper);
       map.set(feCompositeTag.localName().impl(), createSVGFECompositeElementWrapper);
       map.set(feConvolveMatrixTag.localName().impl(), createSVGFEConvolveMatrixElementWrapper);
       map.set(feDiffuseLightingTag.localName().impl(), createSVGFEDiffuseLightingElementWrapper);
       map.set(feDisplacementMapTag.localName().impl(), createSVGFEDisplacementMapElementWrapper);
       map.set(feDistantLightTag.localName().impl(), createSVGFEDistantLightElementWrapper);
       map.set(feFloodTag.localName().impl(), createSVGFEFloodElementWrapper);
       map.set(feFuncATag.localName().impl(), createSVGFEFuncAElementWrapper);
       map.set(feFuncBTag.localName().impl(), createSVGFEFuncBElementWrapper);
       map.set(feFuncGTag.localName().impl(), createSVGFEFuncGElementWrapper);
       map.set(feFuncRTag.localName().impl(), createSVGFEFuncRElementWrapper);
       map.set(feGaussianBlurTag.localName().impl(), createSVGFEGaussianBlurElementWrapper);
       map.set(feImageTag.localName().impl(), createSVGFEImageElementWrapper);
       map.set(feMergeTag.localName().impl(), createSVGFEMergeElementWrapper);
       map.set(feMergeNodeTag.localName().impl(), createSVGFEMergeNodeElementWrapper);
       map.set(feMorphologyTag.localName().impl(), createSVGFEMorphologyElementWrapper);
       map.set(feOffsetTag.localName().impl(), createSVGFEOffsetElementWrapper);
       map.set(fePointLightTag.localName().impl(), createSVGFEPointLightElementWrapper);
       map.set(feSpecularLightingTag.localName().impl(), createSVGFESpecularLightingElementWrapper);
       map.set(feSpotLightTag.localName().impl(), createSVGFESpotLightElementWrapper);
       map.set(feTileTag.localName().impl(), createSVGFETileElementWrapper);
       map.set(feTurbulenceTag.localName().impl(), createSVGFETurbulenceElementWrapper);
       map.set(filterTag.localName().impl(), createSVGFilterElementWrapper);
       map.set(fontTag.localName().impl(), createSVGFontElementWrapper);
       map.set(font_faceTag.localName().impl(), createSVGFontFaceElementWrapper);
       map.set(font_face_formatTag.localName().impl(), createSVGFontFaceFormatElementWrapper);
       map.set(font_face_nameTag.localName().impl(), createSVGFontFaceNameElementWrapper);
       map.set(font_face_srcTag.localName().impl(), createSVGFontFaceSrcElementWrapper);
       map.set(font_face_uriTag.localName().impl(), createSVGFontFaceUriElementWrapper);
       map.set(foreignObjectTag.localName().impl(), createSVGForeignObjectElementWrapper);
       map.set(gTag.localName().impl(), createSVGGElementWrapper);
       map.set(glyphTag.localName().impl(), createSVGGlyphElementWrapper);
       map.set(imageTag.localName().impl(), createSVGImageElementWrapper);
       map.set(lineTag.localName().impl(), createSVGLineElementWrapper);
       map.set(linearGradientTag.localName().impl(), createSVGLinearGradientElementWrapper);
       map.set(markerTag.localName().impl(), createSVGMarkerElementWrapper);
       map.set(maskTag.localName().impl(), createSVGMaskElementWrapper);
       map.set(metadataTag.localName().impl(), createSVGMetadataElementWrapper);
       map.set(missing_glyphTag.localName().impl(), createSVGMissingGlyphElementWrapper);
       map.set(pathTag.localName().impl(), createSVGPathElementWrapper);
       map.set(patternTag.localName().impl(), createSVGPatternElementWrapper);
       map.set(polygonTag.localName().impl(), createSVGPolygonElementWrapper);
       map.set(polylineTag.localName().impl(), createSVGPolylineElementWrapper);
       map.set(radialGradientTag.localName().impl(), createSVGRadialGradientElementWrapper);
       map.set(rectTag.localName().impl(), createSVGRectElementWrapper);
       map.set(scriptTag.localName().impl(), createSVGScriptElementWrapper);
       map.set(setTag.localName().impl(), createSVGSetElementWrapper);
       map.set(stopTag.localName().impl(), createSVGStopElementWrapper);
       map.set(styleTag.localName().impl(), createSVGStyleElementWrapper);
       map.set(svgTag.localName().impl(), createSVGSVGElementWrapper);
       map.set(switchTag.localName().impl(), createSVGSwitchElementWrapper);
       map.set(symbolTag.localName().impl(), createSVGSymbolElementWrapper);
       map.set(textTag.localName().impl(), createSVGTextElementWrapper);
       map.set(textPathTag.localName().impl(), createSVGTextPathElementWrapper);
       map.set(titleTag.localName().impl(), createSVGTitleElementWrapper);
       map.set(trefTag.localName().impl(), createSVGTRefElementWrapper);
       map.set(tspanTag.localName().impl(), createSVGTSpanElementWrapper);
       map.set(useTag.localName().impl(), createSVGUseElementWrapper);
       map.set(viewTag.localName().impl(), createSVGViewElementWrapper);
       map.set(vkernTag.localName().impl(), createSVGVKernElementWrapper);
    }
    CreateSVGElementWrapperFunction createWrapperFunction = map.get(element->localName().impl());
    if (createWrapperFunction)
        return createWrapperFunction(element);
    return V8SVGElement::wrap(element, forceNewObject);
}

}

#endif
