// Copyright (c) Google Inc. 2010
// All rights reserved.
// This file is automatically generated by GRIT. Do not edit.

#pragma once

#define IDR_DEVTOOLS_DEBUGGER_SCRIPT_JS 7000
#define IDR_DEVTOOLS_INJECT_WEBKIT_JS 7001
